version: '3'
services:
  app:
    container_name: inf8102
    image: inf8102
    ports:
      - "8000:8000"
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

